REDIRECT_STATUS=true
SCRIPT_FILENAME=./test1.php
REQUEST_METHOD=POST
GATEWAY_INTERFACE=CGI/1.1
CONTENT_LENGTH=7
export CONTENT_LENGTH
export REDIRECT_STATUS
export SCRIPT_FILENAME
export REQUEST_METHOD
export GATEWAY_INTERFACE
echo "TEST=1" | php-cgi